FROM python:3.8 AS build-env
ADD . /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip install -r ./requirements.txt --target local-site-packages

FROM python:3.8-slim
COPY --from=build-env /app /app
WORKDIR /app
ENV PYTHONPATH=./local-site-packages
CMD ["src/__main__.py"]