FROM python:3.8 AS build-env
ADD . /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip install -r ./requirements.txt --target local-site-packages

FROM gcr.io/distroless/python3
COPY --from=build-env /app /app
WORKDIR /app
#ENV LC_ALL C.UTF-8
ENV PYTHONPATH=./local-site-packages
CMD ["src/__main__.py"]