# Build Stage
FROM maven:3.5-jdk-8 AS build
ADD . /app
WORKDIR /app

RUN mvn -f pom.xml clean package

# Run Stage
FROM openjdk:8-jre-alpine
ARG DEPENDENCY=/usr/src/
COPY --from=build app/target/dependency/BOOT-INF/lib /app/lib
COPY --from=build app/target/dependency/META-INF /app/META-INF
COPY --from=build app/target/dependency/BOOT-INF/classes /app
WORKDIR /app

CMD ["java","-cp","app:app/lib/*","hello.Application"]